### ISSUE TITLE
Template not found in SilverStripe 4.1

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-gridfieldqueuedexport#25] opened 2018-05-18 04:36 UTC
Seems the admin_template isn't found after clicking the button. Might need a configuration update

**Comment by robbieaverill** [comment] 2018-05-18 04:37
Fancy a pull request? 😄

**Comment by Firesphere** [comment] 2018-05-18 04:38
I haven't gotten it working myself! (yet), so... who knows, maybe later?

**Comment by raissanorth** [comment] 2018-08-23 22:54
Hi @Firesphere I cannot reproduce this using 

```
silverstripe/framework                    4.1.2   
silverstripe/gridfieldqueuedexport        2.1.0   
smbiote/silverstripe-queuedjobs          4.2.3   
```
and will therefore close the issue.

Please feel free to open this again, if it still remains an issue. In the latter case, please provide more information on the versions you are using.

Thanks!

**Closed by raissanorth** 2018-08-23 22:54 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug
